### ISSUE TITLE
Failure to start: Cannot find module 'electron-localShortcut'

### ISSUE THREAD

**Issue by zsturgess** [JonSn0w/Hyde#2]
I'm running on Ubuntu 16.04. A 'npm start' yeilds:
```
Warning, the following targets are using a decimal version:

  electron: 1.6

We recommend using a string for minor/patch versions to avoid numbers like 6.10
getting parsed as 6.1, which can lead to unexpected behavior.

App threw an error during load
Error: Cannot find module 'electron-localShortcut'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/zac/Documents/Projects/Personal/hyde/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zac/Documents/Projects/Personal/hyde/main.js:19:21)
    at Object.<anonymous> (/home/zac/Documents/Projects/Personal/hyde/main.js:263:3)
    at Module._compile (module.js:571:32)
    at Object.require.extensions.(anonymous function) [as .js] (/home/zac/Documents/Projects/Personal/hyde/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (module.js:488:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-localShortcut'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/zac/Documents/Projects/Personal/hyde/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/zac/Documents/Projects/Personal/hyde/main.js:19:21)
    at Object.<anonymous> (/home/zac/Documents/Projects/Personal/hyde/main.js:263:3)
    at Module._compile (module.js:571:32)
    at Object.require.extensions.(anonymous function) [as .js] (/home/zac/Documents/Projects/Personal/hyde/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (module.js:488:32)
```

At which, the terminal just hangs.

The following seems to resolve:
```
diff --git a/main.js b/main.js
index 0b2474c..755b439 100644
--- a/main.js
+++ b/main.js
@@ -16,7 +16,7 @@ const keepInTray = config.get('keepInTray');
 const fs = require('fs');
 const path = require('path');
 const mainPage = path.join('file://', __dirname, '/index.html');
-var localShortcut = require('electron-localShortcut');
+var localShortcut = require('electron-localshortcut');
 const {Menu, MenuItem, ipcMain} = require('electron');
 // const window = require('./js/windowManager');
```

**Comment by tterb** [comment]
Okay, I'll investigate this further today and get it squared away.   
Thanks for letting me know
